
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[192] =
    {   0,
       75,   75,   77,   75,    6,    1,   59,   75,   75,   65,
       58,   75,   11,   12,   63,   62,    8,   61,   16,   64,
       75,   75,   15,    7,   40,   67,   42,   74,   13,   14,
       47,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,    9,   66,   10,   60,   44,    0,
        0,    0,    0,    0,   50,   45,   55,    0,    0,   48,
       35,   51,   36,   52,    0,    0,    4,   49,   72,    0,
        0,    0,   14,   13,   37,   39,   43,   41,   38,   74,
       71,   74,    0,   56,   74,   74,   22,   74,   74,   74,
       24,   74,   74,   74,   74,   74,   74,   74,   74,   74,

       57,   46,   68,    0,    0,    0,    0,   73,    0,    0,
        0,    4,   53,   54,   74,   74,   74,   74,   74,   23,
       25,   74,   74,   74,   74,   74,   74,   74,   74,   74,
        0,    0,   69,    0,    0,    0,    5,   74,   17,   74,
       19,   74,   26,   74,   74,   74,   74,   74,   74,   33,
       74,    0,    0,   70,   34,   74,   20,   74,   28,   74,
       74,   74,   74,   21,    0,    0,   18,   27,   29,   30,
       31,   74,    0,    0,   74,    0,    0,    0,   32,    0,
        0,    0,    0,    0,    3,    2,    0,    0,    0,    0,
        0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   27,   44,
       45,   27,   27,   46,   47,   48,   49,   50,   51,   27,
       27,   52,   53,   54,   55,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    1,    5,    5,
        1,    1,    5,    5,    5,    5,    5,    7,    2,    8,
        8,    9,    5,   10,   11,    2,   12,   13,   14,    9,
        5,   15,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,    1,   16,    9,    5
    } ;

static const flex_int16_t yy_base[207] =
    {   0,
        0,    0,  344,  781,  781,  781,  316,  313,   52,  290,
       48,  260,  781,  781,  261,   45,  781,   44,   42,   52,
       47,   54,  252,  781,   54,  247,   55,   54,  781,  781,
      246,    0,   55,   57,   62,   63,   70,   82,   90,   91,
       93,   99,  110,   64,  781,   75,  781,  781,  781,  261,
      133,  125,  224,  199,  781,  781,  781,  226,    0,  781,
      781,  781,  781,  781,  130,  154,    0,  781,  781,  139,
      149,  153,  781,  781,  200,  781,  781,  781,  196,  135,
      781,    0,   71,  781,  140,  145,  149,  154,  151,  163,
      165,  167,  176,  178,  182,  192,  188,  198,  201,  207,

      781,  137,  207,  174,  175,  237,  189,  781,  248,  253,
      260,    0,  781,  781,  225,  229,  242,  244,  247,  253,
      256,  259,  262,  268,  277,  282,  286,  265,  288,  297,
      143,  136,  781,  326,  329,  343,  781,  310,  313,  319,
      315,  324,  328,  333,  330,  345,  343,  354,  357,  359,
      369,  128,   99,  781,  363,  375,  373,  378,  384,  393,
      390,  395,  404,  399,   55,   48,  409,  413,  415,  418,
      424,  430,  132,   27,  433,  147,  455,  158,  439,  463,
      483,  230,  307,  489,  781,  781,  507,  515,  522,  544,
      781,  598,  603,  618,  627,  636,  644,  653,  668,  684,

      700,  716,  729,  738,  749,  764
    } ;

static const flex_int16_t yy_def[207] =
    {   0,
      191,    1,  191,  191,  191,  191,  191,  192,  191,  191,
      191,  193,  191,  191,  191,  191,  191,  191,  191,  191,
      194,  194,  191,  191,  191,  191,  191,  195,  191,  191,
      191,  196,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,   41,  191,  197,  191,  191,  191,  192,
      192,  191,  191,  191,  191,  191,  191,  191,  198,  191,
      191,  191,  191,  191,  199,  200,  201,  191,  191,  191,
      191,  194,  191,  191,  191,  191,  191,  191,  191,   41,
      191,  196,  197,  191,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

      191,  197,  192,  191,  191,  191,  191,  191,  200,  200,
      202,  201,  191,  191,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
      191,  191,  191,  191,  200,  200,  191,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,  191,  191,  191,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,  191,  191,   41,   41,   41,   41,
       41,   41,  203,  191,   41,  203,  203,  204,   41,  191,
      191,  204,  204,  205,  191,  191,  206,  191,  205,  206,
        0,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191
    } ;

static const flex_int16_t yy_nxt[838] =
    {   0,
        4,    5,    6,    4,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,    4,   30,
       31,   32,   28,   33,   34,   35,   36,   37,   28,   28,
       38,   28,   39,   28,   28,   40,   41,   28,   42,   43,
       44,   28,   45,   46,   47,   48,   52,   56,   52,   61,
       63,   65,   65,  178,   70,   66,   71,   71,   64,   62,
       67,   70,   57,   72,   72,   74,   68,   75,   76,   78,
       79,   81,   81,  174,   81,   82,   82,   53,   82,   81,
       81,  173,   54,   82,   82,  191,   86,   81,   81,  101,

       85,   82,   81,  100,   80,   88,   87,   83,   83,   81,
       83,   80,   89,   82,   90,   83,   83,   81,   81,   91,
       81,   82,   82,   83,   82,   92,   81,   94,  102,   52,
       82,   52,   95,   96,   93,   83,  176,   81,  176,   51,
       97,   82,   98,   83,   83,  103,   83,  166,  103,   65,
       65,  176,   83,  176,   99,  103,  110,  110,   65,   65,
       53,  191,  182,   83,   81,   54,   70,  111,   71,   71,
       70,  165,   72,   72,   80,   80,  115,  116,  153,   80,
       80,  183,   80,  152,   80,   80,  103,   80,   80,   80,
       80,   80,   80,   80,   80,  119,   80,  117,   80,  134,

      118,   80,   80,   80,   80,   80,   80,   80,  120,  132,
       80,  131,   80,   51,  121,   80,   80,   80,   80,  122,
      114,   80,   80,   80,  113,  123,  124,   80,   80,   80,
      125,   80,   80,  127,  182,   80,  106,   80,   80,   80,
       80,  129,  105,  126,  128,   80,   80,  130,   80,  133,
      110,  110,  133,  183,   80,  110,  110,  138,  133,  133,
      104,  111,  136,  136,   80,   80,  111,   51,   80,   80,
       84,   77,   80,  111,  139,  140,   80,   73,  137,  142,
      141,   80,   80,   80,   80,   60,   80,   80,   59,   80,
      133,   80,   80,   80,   80,   80,   80,  143,   80,   80,

       80,   80,   80,   80,   80,  149,   80,   80,   80,   80,
      144,  191,   80,  145,   55,   80,   80,   80,  147,   51,
      146,   80,   80,  150,   80,   80,   80,   80,   80,   80,
      191,  110,  110,   80,  148,   80,   80,   80,  154,  151,
       49,  154,  111,  191,   80,  110,  110,  154,  154,   80,
       80,  155,   80,   80,   80,   80,  111,   80,   80,   80,
       80,  156,   80,   80,   80,  191,   80,   80,   80,   80,
       80,  157,   80,   80,  191,   80,  191,  159,  158,  154,
       80,  160,   80,   80,   80,   80,  191,  161,  162,  191,
       80,  191,   80,   80,   80,  163,   80,   80,   80,   80,

      191,   80,   80,   80,   80,  164,   80,  191,   80,   80,
       80,  167,   80,   80,   80,   80,   80,   80,   80,  191,
       80,  168,   80,   80,   80,   80,  191,  170,  169,   80,
       80,   80,   80,   80,   80,   80,  191,   80,   80,   80,
       80,  191,  171,   80,   80,  191,   80,  172,   80,   80,
      191,   80,   80,   80,   80,   80,   80,   80,   80,  180,
       80,  191,   80,   80,   80,   80,  175,  180,  179,   80,
       80,   80,   80,   80,  181,  181,  191,   80,   80,   80,
       80,  191,  181,  181,  185,  185,   80,  185,  191,  185,
      186,  186,  191,  186,  191,  186,  191,  191,  191,  191,

      191,  185,  181,  181,  191,  191,  187,  186,  186,  186,
      191,  186,  191,  186,  188,  191,  186,  186,  191,  186,
      191,  186,  191,  186,  186,  186,  186,  191,  186,  191,
      191,  191,  188,  186,  191,  191,  185,  191,  191,  187,
      186,  191,  186,  191,  191,  186,  186,  188,  186,  191,
      186,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      186,  191,  186,  191,  191,  191,  191,  191,  186,  188,
      191,  191,  191,  191,  191,  186,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  186,   50,   50,

      191,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   58,  191,   58,  191,   58,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,  191,
      191,  191,  191,   69,   80,  191,  191,  191,   80,   80,
      191,   80,   80,   82,  191,  191,  191,   82,  191,  191,
       82,   83,  191,  191,   83,   83,   83,  191,  191,   83,
      107,  191,  191,  191,  107,  191,  191,  191,  107,  108,
      108,  108,  108,  108,  191,  108,  191,  108,  108,  191,
      191,  191,  191,  108,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,

      112,  112,  191,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  177,  191,  177,  191,  191,  191,  191,  191,
      177,  184,  191,  191,  191,  191,  191,  184,  191,  184,
      189,  189,  189,  191,  189,  189,  191,  191,  191,  191,
      189,  191,  191,  191,  189,  190,  190,  190,  191,  190,
      191,  191,  191,  191,  191,  190,  191,  191,  191,  190,
        3,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191
    } ;

static const flex_int16_t yy_chk[838] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,   11,    9,   16,
       18,   19,   19,  174,   21,   20,   21,   21,   18,   16,
       20,   22,   11,   22,   22,   25,   20,   25,   25,   27,
       27,   28,   33,  166,   34,   28,   33,    9,   34,   35,
       36,  165,    9,   35,   36,   83,   34,   37,   83,   46,

       33,   37,   46,   44,   44,   36,   35,   28,   33,   38,
       34,   44,   37,   38,   37,   35,   36,   39,   40,   38,
       41,   39,   40,   37,   41,   38,   42,   40,   46,   52,
       42,   52,   41,   41,   39,   38,  173,   43,  173,   51,
       41,   43,   42,   39,   40,   51,   41,  153,   51,   65,
       65,  176,   42,  176,   43,   51,   66,   66,   70,   70,
       52,  102,  178,   43,  102,   52,   71,   66,   71,   71,
       72,  152,   72,   72,   80,   80,   85,   86,  132,   85,
       85,  178,   80,  131,   86,   86,   51,   85,   87,   87,
       89,   89,   86,   88,   88,   89,   87,   87,   89,  107,

       88,   88,   90,   90,   91,   91,   92,   92,   90,  105,
       90,  104,   91,  103,   92,   93,   93,   94,   94,   93,
       79,   95,   95,   93,   75,   94,   95,   97,   97,   95,
       96,   96,   96,   97,  182,   97,   58,   98,   98,   96,
       99,   99,   54,   96,   98,   98,  100,  100,   99,  106,
      109,  109,  106,  182,  100,  110,  110,  115,  106,  106,
       53,  109,  111,  111,  115,  115,  110,   50,  116,  116,
       31,   26,  115,  111,  116,  117,  116,   23,  111,  119,
      118,  117,  117,  118,  118,   15,  119,  119,   12,  117,
      106,  118,  120,  120,  119,  121,  121,  122,  122,  122,

      120,  123,  123,  121,  128,  128,  122,  124,  124,  123,
      123,  183,  128,  124,   10,  124,  125,  125,  126,    8,
      125,  126,  126,  129,  125,  127,  127,  129,  129,  126,
      183,  135,  135,  127,  127,  129,  130,  130,  134,  130,
        7,  134,  135,    3,  130,  136,  136,  134,  134,  138,
      138,  138,  139,  139,  141,  141,  136,  138,  140,  140,
      139,  140,  141,  142,  142,    0,  140,  143,  143,  145,
      145,  142,  144,  144,    0,  143,    0,  145,  144,  134,
      144,  146,  147,  147,  146,  146,    0,  147,  148,    0,
      147,    0,  146,  148,  148,  149,  149,  149,  150,  150,

        0,  148,  155,  155,  149,  151,  150,    0,  151,  151,
      155,  156,  157,  157,  156,  156,  151,  158,  158,    0,
      157,  158,  156,  159,  159,  158,    0,  161,  160,  161,
      161,  159,  160,  160,  162,  162,    0,  161,  164,  164,
      160,    0,  162,  163,  163,    0,  164,  163,  167,  167,
        0,  163,  168,  168,  169,  169,  167,  170,  170,  177,
      168,  177,  169,  171,  171,  170,  172,  180,  175,  172,
      172,  171,  175,  175,  177,  177,    0,  172,  179,  179,
      175,    0,  180,  180,  181,  181,  179,  181,    0,  181,
      184,  184,    0,  184,    0,  184,    0,    0,    0,    0,

        0,  181,  181,  181,    0,    0,  184,  184,  187,  187,
        0,  187,    0,  187,  184,    0,  188,  188,    0,  188,
        0,  188,    0,  189,  189,  187,  189,    0,  189,    0,
        0,    0,  187,  188,    0,    0,  181,    0,    0,  189,
      189,    0,  184,    0,    0,  190,  190,  189,  190,    0,
      190,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      187,    0,  190,    0,    0,    0,    0,    0,  188,  190,
        0,    0,    0,    0,    0,  189,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  190,  192,  192,

        0,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  193,    0,  193,    0,  193,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,    0,
        0,    0,    0,  194,  195,    0,    0,    0,  195,  195,
        0,  195,  195,  196,    0,    0,    0,  196,    0,    0,
      196,  197,    0,    0,  197,  197,  197,    0,    0,  197,
      198,    0,    0,    0,  198,    0,    0,    0,  198,  199,
      199,  199,  199,  199,    0,  199,    0,  199,  199,    0,
        0,    0,    0,  199,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,

      201,  201,    0,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  203,    0,  203,    0,    0,    0,    0,    0,
      203,  204,    0,    0,    0,    0,    0,  204,    0,  204,
      205,  205,  205,    0,  205,  205,    0,    0,    0,    0,
      205,    0,    0,    0,  205,  206,  206,  206,    0,  206,
        0,    0,    0,    0,    0,  206,    0,    0,    0,  206,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "file.l"
#line 2 "file.l"
	#include <stdio.h>
	#include <string.h>
	#include "y.tab.h"

	#define ANSI_COLOR_RED		"\x1b[31m"
	#define ANSI_COLOR_GREEN	"\x1b[32m"
	#define ANSI_COLOR_YELLOW	"\x1b[33m"
	#define ANSI_COLOR_BLUE		"\x1b[34m"
	#define ANSI_COLOR_MAGENTA	"\x1b[35m"
	#define ANSI_COLOR_CYAN		"\x1b[36m"
	#define ANSI_COLOR_RESET	"\x1b[0m"

	struct symboltable
	{
		char name[100];
		char class[100];
		char type[100];
		char value[100];
		int initnestval;
		int nestval;
		int lineno;
		int length;
		int params_count;
		int brackets;
		char params_types[100][100];
	}ST[1001];

	struct constanttable
	{
		char name[100];
		char type[100];
		int length;
	}CT[1001];
/*
	struct proc_decl
	{
		char name[100];
		char lineno;
		int params_count;
		char params_types[100][100];
		char ret_type[100];
	}PT[1001];
	*/
	int currnest = 0;
	//int params_count = 0;
	//int call_params_count = 0;
	extern int yylval;
	int arrbrackets = 0;
	int totbrackets = 0;

	int hash(char *str)
	{
		int value = 0;
		for(int i = 0 ; i < strlen(str) ; i++)
		{
			value = 10*value + (str[i] - 'A');
			value = value % 1001;
			while(value < 0)
				value = value + 1001;
		}
		return value;
	}

	int getbrackets(char *str1){
		int value = hash(str1);
		if(ST[value].length == 0)
			return 12;
		if(strcmp(ST[value].name,str1)==0)
			return ST[value].brackets;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					return ST[i].brackets;
				}
			}
			return 13;
		}
	}

	void setbrackets(char *str1, int brackets){
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0 )
			{
				ST[i].brackets = brackets;
				return;
			}
		}
	}


	int lookupST(char *str)
	{
		int value = hash(str);
		if(ST[value].length == 0)
		{
			return 0;
		}
		else if(strcmp(ST[value].name,str)==0)
		{

			return value;
		}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str)==0)
				{

					return i;
				}
			}
			return 0;
		}
	}

	int lookupCT(char *str)
	{
		int value = hash(str);
		if(CT[value].length == 0)
			return 0;
		else if(strcmp(CT[value].name,str)==0)
			return 1;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(CT[i].name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}


	void insertSTline(char *str1, int line)
	{
		int value = hash(str1);
		if(strcmp(ST[value].name,str1)==0)
			ST[value].lineno = line;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					ST[i].lineno = line;
				}
			}
		}
	}

	void insertSTparamstype(char *str1, char *str2)
	{
		int value = hash(str1);
	    if(strcmp(ST[value].name,str1)==0)
			{
				for(int j=0;j<100;j++)
				{
					if(ST[value].params_types[j][0]=='\0')
					{
						strcpy(ST[value].params_types[j],str2);
						break;
					}
				}
			}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					for(int j=0;j<100;j++)
					{
						if(ST[i].params_types[j][0]=='\0')
						{
							strcpy(ST[i].params_types[j],str2);
							break;
						}
					}
				}
			}
		}

	}

	int check_params_type(char *str, char types[100][100], int n)
	{
		int value = hash(str);
	    if(strcmp(ST[value].name,str)==0)
			{
				for(int j=0;j<n;j++)
				{
					if(strcmp(ST[value].params_types[j],types[j]))
					{
						/*
						for(int k=0;k<n;k++)
						{
							printf("\n%s\n",ST[value].params_types[j]);
						}
						printf("\n%s....%s....%s....%d\n",ST[value].name,ST[value].params_types[j],types[j],j);
						*/
						return 0;
					}
				}
			}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str)==0)
				{
					for(int j=0;j<n;j++)
					{
						if(strcmp(ST[i].params_types[j],types[j]))
						{
							/*
							for(int k=0;k<n;k++)
							{
								printf("\n%s\n",ST[i].params_types[j]);
							}
							printf("\n%s....%s....%s....%d\n",ST[i].name,ST[i].params_types[j],types[j],j);
							*/
							return 0;
						}
					}
				}
			}
		}


		return 1;
	}

	void insertST(char *str1, char *str2)
	{
		if(lookupST(str1))
		{
			if(strcmp(ST[lookupST(str1)].class,"Identifier")==0 && strcmp(str2,"Array Identifier")==0)
			{
				printf("ERROR: Non array used as array.\n");
				exit(0);
			}
			return;
		}
		else
		{
			int value = hash(str1);
			if(ST[value].length == 0)
			{
				strcpy(ST[value].name,str1);
				strcpy(ST[value].class,str2);
				ST[value].length = strlen(str1);
				ST[value].initnestval = 9999;
				ST[value].nestval = 9999;
				ST[value].params_count = -1;
				insertSTline(str1,yylineno);
				for(int j=0;j<100;j++)
					ST[value].params_types[j][0] = '\0';
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,str1);
			strcpy(ST[pos].class,str2);
			ST[pos].length = strlen(str1);
			ST[pos].initnestval = 9999;
			ST[pos].nestval = 9999;
			ST[pos].params_count = -1;
			for(int j=0;j<100;j++)
				ST[value].params_types[j][0] = '\0';
		}
	}

	void insertSTtype(char *str1, char *str2)
	{
		int value = hash(str1);
		if(strcmp(ST[value].name,str1)==0)
			strcpy(ST[value].type,str2);
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					strcpy(ST[i].type,str2);
				}
			}
		}


    }

	void insertSTvalue(char *str1, char *str2)
	{
		int value = hash(str1);
		if(strcmp(ST[value].name,str1)==0 && ST[value].nestval == currnest)
			strcpy(ST[value].value,str2);
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0 && ST[i].nestval == currnest)
				{
					strcpy(ST[i].value,str2);
				}
			}
		}

	}


	void insertSTnest(char *s, int nest)
	{
		if(lookupST(s) && ST[lookupST(s)].nestval != 9999)
		{
             int pos = 0;
             int value = hash(s);
			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,s);
			strcpy(ST[pos].class,"Identifier");
			ST[pos].length = strlen(s);
			ST[pos].initnestval = nest;
			ST[pos].nestval = nest;
			ST[pos].params_count = -1;
			ST[pos].lineno = yylineno;
		}
		else
		{
			for(int i = 0 ; i < 1001 ; i++)
			{
				if(strcmp(ST[i].name,s)==0 )
				{
					ST[i].initnestval = nest;
					ST[i].nestval = nest;
				}
			}
		}
	}

	void insertSTparamscount(char *s, int count)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			ST[value].params_count = count;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					ST[i].params_count = count;
				}
			}
		}

	}

	int getSTparamscount(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			return ST[value].params_count;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].params_count;
				}
			}
		}

		return -2;
	}

	void insertSTF(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			strcpy(ST[value].class,"Function");
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					strcpy(ST[i].class,"Function");
				}
			}
		}



	}

	void insertCT(char *str1, char *str2)
	{
		if(lookupCT(str1))
			return;
		else
		{
			int value = hash(str1);
			if(CT[value].length == 0)
			{
				strcpy(CT[value].name,str1);
				strcpy(CT[value].type,str2);
				CT[value].length = strlen(str1);
				return;
			}

			int pos = 0;

			for (int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(CT[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(CT[pos].name,str1);
			strcpy(CT[pos].type,str2);
			CT[pos].length = strlen(str1);
		}
	}

	void deletedata (int nesting)
	{
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(ST[i].nestval == nesting)
			{
				ST[i].nestval = 99999;
			}
		}


	}


	int checkscope(char *s)
	{
		int flag = 0;
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(ST[i].nestval > currnest)
				{
					flag = 1;
				}
				else
				{
					flag = 0;
					break;
				}
			}
		}
		if(!flag)
		{
			return 1;
		}
		else
		{
			return 0;
		}
	}

	int check_id_is_func(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
		{
			if(strcmp(ST[value].class,"Function")==0)
					return 1;
		}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					if(strcmp(ST[i].class,"Function")==0);
					return 1;
				}
			}
		}
		return 0;
	}

	int checkarray(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			{
				if(strcmp(ST[value].class,"Array Identifier")==0)
				{
					return 0;
				}
			}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					if(strcmp(ST[i].class,"Array Identifier")==0)
					{
						return 0;
					}
				}
			}
		}

		return 1;
	}

	int duplicate(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			{
				if(ST[value].nestval == currnest)
				{
			        return 1;
				}
			}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					if(ST[i].nestval == currnest)
					{
						return 1;
					}
				}
			}
		}

		return 0;
	}

	int check_duplicate(char* str)
	{
		int value = hash(str);
		if(strcmp(ST[value].name, str) == 0 && strcmp(ST[value].class, "Function") == 0)
			{
				printf("Function redeclaration not allowed\n");
				exit(0);
			}
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0)
				{
					printf("Function redeclaration not allowed\n");
					exit(0);
				}
			}
		}

	}

	int check_declaration(char* str, char *check_type)
	{
		int value = hash(str);
		if(strcmp(ST[value].name, str) == 0 && strcmp(ST[value].class, "Function") == 0 || strcmp(ST[value].name,"printf")==0 )
				return 1;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0 || strcmp(ST[i].name,"printf")==0)
				{
                    return 1;
    			}
			}
		}

		return 0;
	}

	int check_params(char* type_specifier)
	{
		if(!strcmp(type_specifier, "void"))
		{
			printf("Parameters cannot be of type void\n");
			exit(0);
		}
		return 0;
	}

	char gettype(char *s, int flag)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			return ST[value].type[0];
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].type[0];
				}
			}
		}

	}

	char *gettypestr(char *s)
	{	int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			return ST[value].type;
		else
		{
			for(int i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].type;
				}
			}
		}

	}

	void printST()
	{
		printf("%10s | %15s | %10s | %10s | %10s | %15s | %15s | %10s |\n","SYMBOL", "CLASS", "TYPE","VALUE", "LINE NO", "NESTING", "PARAMS COUNT", "ARRAY DIM.");
		for(int i=0;i<100;i++) {
			printf("-");
		}
		printf("\n");
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(ST[i].length == 0)
			{
				continue;
			}
			printf("%10s | %15s | %10s | %10s | %10d | %15d | %15d | %10d |\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, ST[i].lineno, ST[i].initnestval, ST[i].params_count, ST[i].brackets);
		}
		for(int i=0;i<1001;i++)
		{
			if(!strcmp(ST[i].class,"Function"))
			{
				printf("\n%s : ",ST[i].name);
				for(int j=0;j<ST[i].params_count;j++)
				{
					printf(" %s ",ST[i].params_types[j]);
				}
			}
		}
    }


	void printCT()
	{
		printf("%10s | %15s\n","NAME", "TYPE");
		for(int i=0;i<81;i++) {
			printf("-");
		}
		printf("\n");
		for(int i = 0 ; i < 1001 ; i++)
		{
			if(CT[i].length == 0)
				continue;

			printf("%10s | %15s\n",CT[i].name, CT[i].type);
		}
	}
	char curid[20];
	char curtype[20];
	char curval[20];

#line 1399 "lex.yy.c"
#line 1400 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 712 "file.l"

#line 1619 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 192 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 781 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 713 "file.l"
{yylineno++;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 714 "file.l"
{ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 715 "file.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 716 "file.l"
{ }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 717 "file.l"
{ }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 718 "file.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 719 "file.l"
{ return(';'); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 720 "file.l"
{ return(','); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 721 "file.l"
{ return('{'); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 722 "file.l"
{ return('}'); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 723 "file.l"
{ return('('); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 724 "file.l"
{ return(')'); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 725 "file.l"
{ return('['); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 726 "file.l"
{ return(']'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 727 "file.l"
{ return(':'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 728 "file.l"
{ return('.'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 730 "file.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return CHAR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 731 "file.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 732 "file.l"
{ insertST(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 733 "file.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return FLOAT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 734 "file.l"
{ insertST(yytext, "Keyword"); return WHILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 735 "file.l"
{ insertST(yytext, "Keyword"); return DO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 736 "file.l"
{ insertST(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 737 "file.l"
{ insertST(yytext, "Keyword"); return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 738 "file.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return INT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 739 "file.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return LONG;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 740 "file.l"
{ insertST(yytext, "Keyword"); return RETURN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 741 "file.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return SHORT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 742 "file.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return SIGNED;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 743 "file.l"
{ insertST(yytext, "Keyword"); return SIZEOF;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 744 "file.l"
{ strcpy(curtype,yytext);   insertST(yytext, "Keyword");  return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 745 "file.l"
{ insertST(yytext, "Keyword");   return UNSIGNED;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 746 "file.l"
{ strcpy(curtype,yytext);   insertST(yytext, "Keyword");  return VOID;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 747 "file.l"
{ insertST(yytext, "Keyword");  return BREAK;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 751 "file.l"
{ return increment_operator; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 752 "file.l"
{ return decrement_operator; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 753 "file.l"
{ return leftshift_operator; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 754 "file.l"
{ return rightshift_operator; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 755 "file.l"
{ return lessthan_assignment_operator; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 756 "file.l"
{ return lessthan_operator; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 757 "file.l"
{ return greaterthan_assignment_operator; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 758 "file.l"
{ return greaterthan_operator; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 759 "file.l"
{ return equality_operator; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 760 "file.l"
{ return inequality_operator; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 761 "file.l"
{ return AND_operator; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 762 "file.l"
{ return OR_operator; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 763 "file.l"
{ return caret_operator; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 764 "file.l"
{ return multiplication_assignment_operator; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 765 "file.l"
{ return division_assignment_operator; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 766 "file.l"
{ return modulo_assignment_operator; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 767 "file.l"
{ return addition_assignment_operator; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 768 "file.l"
{ return subtraction_assignment_operator; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 769 "file.l"
{ return leftshift_assignment_operator; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 770 "file.l"
{ return rightshift_assignment_operator; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 771 "file.l"
{ return AND_assignment_operator; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 772 "file.l"
{ return XOR_assignment_operator; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 773 "file.l"
{ return OR_assignment_operator; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 774 "file.l"
{ return amp_operator; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 775 "file.l"
{ return exclamation_operator; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 776 "file.l"
{ return tilde_operator; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 777 "file.l"
{ return subtract_operator; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 778 "file.l"
{ return add_operator; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 779 "file.l"
{ return multiplication_operator; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 780 "file.l"
{ return division_operator; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 781 "file.l"
{ return modulo_operator; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 782 "file.l"
{ return pipe_operator; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 783 "file.l"
{ return assignment_operator;}
	YY_BREAK
case 68:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 785 "file.l"
{strcpy(curval,yytext); insertCT(yytext,"String Constant"); return string_constant;}
	YY_BREAK
case 69:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 786 "file.l"
{strcpy(curval,yytext); insertCT(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 70:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 787 "file.l"
{strcpy(curval,yytext); insertCT(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 71:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 788 "file.l"
{strcpy(curid,yytext); insertST(yytext, "Array Identifier");  return array_identifier;}
	YY_BREAK
case 72:
/* rule 72 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 789 "file.l"
{strcpy(curval,yytext); insertCT(yytext, "Number Constant"); yylval = atoi(yytext); return integer_constant;}
	YY_BREAK
case 73:
/* rule 73 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 790 "file.l"
{strcpy(curval,yytext); insertCT(yytext, "Floating Constant"); return float_constant;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 791 "file.l"
{strcpy(curid,yytext); insertST(curid,"Identifier"); return identifier;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 792 "file.l"
{
		if(yytext[0]=='#')
		{
			printf("ERROR : Pre-Processor directive at line no. %d couldn't be resolved.\n",yylineno);
		}
		else if(yytext[0]=='/')
		{
			printf("ERROR : Unmatched comment at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='"')
		{
			printf("ERROR : String not terminated, at line no. %d\n",yylineno);
		}
		else
		{
			printf("ERROR : Please check line no. %d\n",yylineno);
		}
		printf("%s\n", yytext);
		return 0;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 813 "file.l"
ECHO;
	YY_BREAK
#line 2110 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 192 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 192 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 191);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 813 "file.l"


