/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
static yyconst short int yy_acclist[250] =
    {   0,
       75,   75,   77,   75,   76,    6,   75,   76,    1,    6,
       76,   59,   75,   76,   75,   76,   75,   76,   65,   75,
       76,   58,   75,   76,   75,   76,   11,   75,   76,   12,
       75,   76,   63,   75,   76,   62,   75,   76,    8,   75,
       76,   61,   75,   76,   16,   75,   76,   64,   75,   76,
       75,   76,   75,   76,   15,   75,   76,    7,   75,   76,
       40,   75,   76,   67,   75,   76,   42,   75,   76,   74,
       75,   76,   13,   75,   76,   14,   75,   76,   47,   75,
       76,   74,   75,   76,   74,   75,   76,   74,   75,   76,
       74,   75,   76,   74,   75,   76,   74,   75,   76,   74,

       75,   76,   74,   75,   76,   74,   75,   76,   74,   75,
       76,   74,   75,   76,   74,   75,   76,   74,   75,   76,
        9,   75,   76,   66,   75,   76,   10,   75,   76,   60,
       75,   76,   44,   50,   45,   55,   48,   35,   51,   36,
       52,    4,   49,   72,   14,   13,   37,   39,   43,   41,
       38,   74,   71,   74,   56,   74,   74,   22,   74,   74,
       74,   74,   24,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   57,   46,   68,   73,    4,   53,   54,
       74,   74,   74,   74,   74,   23,   74,   25,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   69,    5,

       74,   17,   74,   74,   19,   74,   74,   26,   74,   74,
       74,   74,   74,   74,   74,   33,   74,   74,   70,   34,
       74,   74,   20,   74,   74,   28,   74,   74,   74,   74,
       74,   21,   74,   18,   74,   27,   74,   29,   74,   30,
       74,   31,   74,   74,   74,   32,   74,    3,    2
    } ;

static yyconst short int yy_accept[193] =
    {   0,
        1,    2,    3,    4,    6,    9,   12,   15,   17,   19,
       22,   25,   27,   30,   33,   36,   39,   42,   45,   48,
       51,   53,   55,   58,   61,   64,   67,   70,   73,   76,
       79,   82,   85,   88,   91,   94,   97,  100,  103,  106,
      109,  112,  115,  118,  121,  124,  127,  130,  133,  134,
      134,  134,  134,  134,  134,  135,  136,  137,  137,  137,
      138,  139,  140,  141,  142,  142,  142,  143,  144,  145,
      145,  145,  145,  146,  147,  148,  149,  150,  151,  152,
      153,  154,  155,  155,  156,  157,  158,  160,  161,  162,
      163,  165,  166,  167,  168,  169,  170,  171,  172,  173,

      174,  175,  176,  177,  177,  177,  177,  177,  178,  178,
      178,  178,  179,  180,  181,  182,  183,  184,  185,  186,
      188,  190,  191,  192,  193,  194,  195,  196,  197,  198,
      199,  199,  199,  200,  200,  200,  200,  201,  202,  204,
      205,  207,  208,  210,  211,  212,  213,  214,  215,  216,
      218,  219,  219,  219,  220,  222,  223,  225,  226,  228,
      229,  230,  231,  232,  234,  234,  234,  236,  238,  240,
      242,  244,  245,  245,  245,  246,  246,  246,  246,  248,
      248,  248,  248,  248,  248,  249,  250,  250,  250,  250,
      250,  250

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    8,    1,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,   23,   24,
       25,   26,    1,    1,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   30,   31,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   27,   42,   43,   27,   44,
       45,   27,   27,   46,   47,   48,   49,   50,   51,   27,
       27,   52,   53,   54,   55,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[57] =
    {   0,
        1,    2,    3,    1,    4,    5,    6,    1,    5,    5,
        1,    1,    5,    5,    5,    5,    5,    7,    2,    8,
        8,    9,    5,   10,   11,    2,   12,   13,   14,    9,
        5,   15,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,    1,   16,    9,    5
    } ;

static yyconst short int yy_base[207] =
    {   0,
        0,    0,  344,  781,  781,  781,  316,  313,   52,  290,
       48,  260,  781,  781,  261,   45,  781,   44,   42,   52,
       47,   54,  252,  781,   54,  247,   55,   54,  781,  781,
      246,    0,   55,   57,   62,   63,   70,   82,   90,   91,
       93,   99,  110,   64,  781,   75,  781,  781,  781,  261,
      133,  125,  224,  199,  781,  781,  781,  226,    0,  781,
      781,  781,  781,  781,  130,  154,    0,  781,  781,  139,
      149,  153,  781,  781,  200,  781,  781,  781,  196,  135,
      781,    0,   71,  781,  140,  145,  149,  154,  151,  163,
      165,  167,  176,  178,  182,  192,  188,  198,  201,  207,

      781,  137,  207,  174,  175,  237,  189,  781,  248,  253,
      260,    0,  781,  781,  225,  229,  242,  244,  247,  253,
      256,  259,  262,  268,  277,  282,  286,  265,  288,  297,
      143,  136,  781,  326,  329,  343,  781,  310,  313,  319,
      315,  324,  328,  333,  330,  345,  343,  354,  357,  359,
      369,  128,   99,  781,  363,  375,  373,  378,  384,  393,
      390,  395,  404,  399,   55,   48,  409,  413,  415,  418,
      424,  430,  132,   27,  433,  147,  455,  158,  439,  463,
      483,  230,  307,  489,  781,  781,  507,  515,  522,  544,
      781,  598,  603,  618,  627,  636,  644,  653,  668,  684,

      700,  716,  729,  738,  749,  764
    } ;

static yyconst short int yy_def[207] =
    {   0,
      191,    1,  191,  191,  191,  191,  191,  192,  191,  191,
      191,  193,  191,  191,  191,  191,  191,  191,  191,  191,
      194,  194,  191,  191,  191,  191,  191,  195,  191,  191,
      191,  196,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,   41,  191,  197,  191,  191,  191,  192,
      192,  191,  191,  191,  191,  191,  191,  191,  198,  191,
      191,  191,  191,  191,  199,  200,  201,  191,  191,  191,
      191,  194,  191,  191,  191,  191,  191,  191,  191,   41,
      191,  196,  197,  191,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,

      191,  197,  192,  191,  191,  191,  191,  191,  200,  200,
      202,  201,  191,  191,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
      191,  191,  191,  191,  200,  200,  191,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
       41,  191,  191,  191,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,  191,  191,   41,   41,   41,   41,
       41,   41,  203,  191,   41,  203,  203,  204,   41,  191,
      191,  204,  204,  205,  191,  191,  206,  191,  205,  206,
        0,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191
    } ;

static yyconst short int yy_nxt[838] =
    {   0,
        4,    5,    6,    4,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,    4,   30,
       31,   32,   28,   33,   34,   35,   36,   37,   28,   28,
       38,   28,   39,   28,   28,   40,   41,   28,   42,   43,
       44,   28,   45,   46,   47,   48,   52,   56,   52,   61,
       63,   65,   65,  178,   70,   66,   71,   71,   64,   62,
       67,   70,   57,   72,   72,   74,   68,   75,   76,   78,
       79,   81,   81,  174,   81,   82,   82,   53,   82,   81,
       81,  173,   54,   82,   82,  191,   86,   81,   81,  101,

       85,   82,   81,  100,   80,   88,   87,   83,   83,   81,
       83,   80,   89,   82,   90,   83,   83,   81,   81,   91,
       81,   82,   82,   83,   82,   92,   81,   94,  102,   52,
       82,   52,   95,   96,   93,   83,  176,   81,  176,   51,
       97,   82,   98,   83,   83,  103,   83,  166,  103,   65,
       65,  176,   83,  176,   99,  103,  110,  110,   65,   65,
       53,  191,  182,   83,   81,   54,   70,  111,   71,   71,
       70,  165,   72,   72,   80,   80,  115,  116,  153,   80,
       80,  183,   80,  152,   80,   80,  103,   80,   80,   80,
       80,   80,   80,   80,   80,  119,   80,  117,   80,  134,

      118,   80,   80,   80,   80,   80,   80,   80,  120,  132,
       80,  131,   80,   51,  121,   80,   80,   80,   80,  122,
      114,   80,   80,   80,  113,  123,  124,   80,   80,   80,
      125,   80,   80,  127,  182,   80,  106,   80,   80,   80,
       80,  129,  105,  126,  128,   80,   80,  130,   80,  133,
      110,  110,  133,  183,   80,  110,  110,  138,  133,  133,
      104,  111,  136,  136,   80,   80,  111,   51,   80,   80,
       84,   77,   80,  111,  139,  140,   80,   73,  137,  142,
      141,   80,   80,   80,   80,   60,   80,   80,   59,   80,
      133,   80,   80,   80,   80,   80,   80,  143,   80,   80,

       80,   80,   80,   80,   80,  149,   80,   80,   80,   80,
      144,  191,   80,  145,   55,   80,   80,   80,  147,   51,
      146,   80,   80,  150,   80,   80,   80,   80,   80,   80,
      191,  110,  110,   80,  148,   80,   80,   80,  154,  151,
       49,  154,  111,  191,   80,  110,  110,  154,  154,   80,
       80,  155,   80,   80,   80,   80,  111,   80,   80,   80,
       80,  156,   80,   80,   80,  191,   80,   80,   80,   80,
       80,  157,   80,   80,  191,   80,  191,  159,  158,  154,
       80,  160,   80,   80,   80,   80,  191,  161,  162,  191,
       80,  191,   80,   80,   80,  163,   80,   80,   80,   80,

      191,   80,   80,   80,   80,  164,   80,  191,   80,   80,
       80,  167,   80,   80,   80,   80,   80,   80,   80,  191,
       80,  168,   80,   80,   80,   80,  191,  170,  169,   80,
       80,   80,   80,   80,   80,   80,  191,   80,   80,   80,
       80,  191,  171,   80,   80,  191,   80,  172,   80,   80,
      191,   80,   80,   80,   80,   80,   80,   80,   80,  180,
       80,  191,   80,   80,   80,   80,  175,  180,  179,   80,
       80,   80,   80,   80,  181,  181,  191,   80,   80,   80,
       80,  191,  181,  181,  185,  185,   80,  185,  191,  185,
      186,  186,  191,  186,  191,  186,  191,  191,  191,  191,

      191,  185,  181,  181,  191,  191,  187,  186,  186,  186,
      191,  186,  191,  186,  188,  191,  186,  186,  191,  186,
      191,  186,  191,  186,  186,  186,  186,  191,  186,  191,
      191,  191,  188,  186,  191,  191,  185,  191,  191,  187,
      186,  191,  186,  191,  191,  186,  186,  188,  186,  191,
      186,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      186,  191,  186,  191,  191,  191,  191,  191,  186,  188,
      191,  191,  191,  191,  191,  186,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  186,   50,   50,

      191,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   58,  191,   58,  191,   58,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,  191,
      191,  191,  191,   69,   80,  191,  191,  191,   80,   80,
      191,   80,   80,   82,  191,  191,  191,   82,  191,  191,
       82,   83,  191,  191,   83,   83,   83,  191,  191,   83,
      107,  191,  191,  191,  107,  191,  191,  191,  107,  108,
      108,  108,  108,  108,  191,  108,  191,  108,  108,  191,
      191,  191,  191,  108,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,

      112,  112,  191,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  135,  135,  135,  135,
      135,  135,  135,  135,  135,  135,  135,  135,  135,  135,
      135,  135,  177,  191,  177,  191,  191,  191,  191,  191,
      177,  184,  191,  191,  191,  191,  191,  184,  191,  184,
      189,  189,  189,  191,  189,  189,  191,  191,  191,  191,
      189,  191,  191,  191,  189,  190,  190,  190,  191,  190,
      191,  191,  191,  191,  191,  190,  191,  191,  191,  190,
        3,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191
    } ;

static yyconst short int yy_chk[838] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,   11,    9,   16,
       18,   19,   19,  174,   21,   20,   21,   21,   18,   16,
       20,   22,   11,   22,   22,   25,   20,   25,   25,   27,
       27,   28,   33,  166,   34,   28,   33,    9,   34,   35,
       36,  165,    9,   35,   36,   83,   34,   37,   83,   46,

       33,   37,   46,   44,   44,   36,   35,   28,   33,   38,
       34,   44,   37,   38,   37,   35,   36,   39,   40,   38,
       41,   39,   40,   37,   41,   38,   42,   40,   46,   52,
       42,   52,   41,   41,   39,   38,  173,   43,  173,   51,
       41,   43,   42,   39,   40,   51,   41,  153,   51,   65,
       65,  176,   42,  176,   43,   51,   66,   66,   70,   70,
       52,  102,  178,   43,  102,   52,   71,   66,   71,   71,
       72,  152,   72,   72,   80,   80,   85,   86,  132,   85,
       85,  178,   80,  131,   86,   86,   51,   85,   87,   87,
       89,   89,   86,   88,   88,   89,   87,   87,   89,  107,

       88,   88,   90,   90,   91,   91,   92,   92,   90,  105,
       90,  104,   91,  103,   92,   93,   93,   94,   94,   93,
       79,   95,   95,   93,   75,   94,   95,   97,   97,   95,
       96,   96,   96,   97,  182,   97,   58,   98,   98,   96,
       99,   99,   54,   96,   98,   98,  100,  100,   99,  106,
      109,  109,  106,  182,  100,  110,  110,  115,  106,  106,
       53,  109,  111,  111,  115,  115,  110,   50,  116,  116,
       31,   26,  115,  111,  116,  117,  116,   23,  111,  119,
      118,  117,  117,  118,  118,   15,  119,  119,   12,  117,
      106,  118,  120,  120,  119,  121,  121,  122,  122,  122,

      120,  123,  123,  121,  128,  128,  122,  124,  124,  123,
      123,  183,  128,  124,   10,  124,  125,  125,  126,    8,
      125,  126,  126,  129,  125,  127,  127,  129,  129,  126,
      183,  135,  135,  127,  127,  129,  130,  130,  134,  130,
        7,  134,  135,    3,  130,  136,  136,  134,  134,  138,
      138,  138,  139,  139,  141,  141,  136,  138,  140,  140,
      139,  140,  141,  142,  142,    0,  140,  143,  143,  145,
      145,  142,  144,  144,    0,  143,    0,  145,  144,  134,
      144,  146,  147,  147,  146,  146,    0,  147,  148,    0,
      147,    0,  146,  148,  148,  149,  149,  149,  150,  150,

        0,  148,  155,  155,  149,  151,  150,    0,  151,  151,
      155,  156,  157,  157,  156,  156,  151,  158,  158,    0,
      157,  158,  156,  159,  159,  158,    0,  161,  160,  161,
      161,  159,  160,  160,  162,  162,    0,  161,  164,  164,
      160,    0,  162,  163,  163,    0,  164,  163,  167,  167,
        0,  163,  168,  168,  169,  169,  167,  170,  170,  177,
      168,  177,  169,  171,  171,  170,  172,  180,  175,  172,
      172,  171,  175,  175,  177,  177,    0,  172,  179,  179,
      175,    0,  180,  180,  181,  181,  179,  181,    0,  181,
      184,  184,    0,  184,    0,  184,    0,    0,    0,    0,

        0,  181,  181,  181,    0,    0,  184,  184,  187,  187,
        0,  187,    0,  187,  184,    0,  188,  188,    0,  188,
        0,  188,    0,  189,  189,  187,  189,    0,  189,    0,
        0,    0,  187,  188,    0,    0,  181,    0,    0,  189,
      189,    0,  184,    0,    0,  190,  190,  189,  190,    0,
      190,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      187,    0,  190,    0,    0,    0,    0,    0,  188,  190,
        0,    0,    0,    0,    0,  189,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  190,  192,  192,

        0,  192,  192,  192,  192,  192,  192,  192,  192,  192,
      192,  192,  192,  192,  193,    0,  193,    0,  193,  194,
      194,  194,  194,  194,  194,  194,  194,  194,  194,    0,
        0,    0,    0,  194,  195,    0,    0,    0,  195,  195,
        0,  195,  195,  196,    0,    0,    0,  196,    0,    0,
      196,  197,    0,    0,  197,  197,  197,    0,    0,  197,
      198,    0,    0,    0,  198,    0,    0,    0,  198,  199,
      199,  199,  199,  199,    0,  199,    0,  199,  199,    0,
        0,    0,    0,  199,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,

      201,  201,    0,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  203,    0,  203,    0,    0,    0,    0,    0,
      203,  204,    0,    0,    0,    0,    0,  204,    0,  204,
      205,  205,  205,    0,  205,  205,    0,    0,    0,    0,
      205,    0,    0,    0,  205,  206,  206,  206,    0,  206,
        0,    0,    0,    0,    0,  206,    0,    0,    0,  206,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,

      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 ".\\filewind.l"
#define INITIAL 0
#line 3 ".\\filewind.l"
	#include <stdio.h>
	#include <string.h>
	#include "y.tab.h"



	struct symboltable
	{
		char name[100];
		char class[100];
		char type[100];
		char value[100];
		int initnestval;
		int nestval;
		int lineno;
		int length;
		int params_count;
		int brackets;
		char params_types[100][100];
	}ST[1001];

	struct constanttable
	{
		char name[100];
		char type[100];
		int length;
	}CT[1001];
/*
	struct proc_decl
	{
		char name[100];
		char lineno;
		int params_count;
		char params_types[100][100];
		char ret_type[100];
	}PT[1001];
	*/
	int currnest = 0;
	//int params_count = 0;
	//int call_params_count = 0;
	extern int yylval;
	int arrbrackets = 0;
	int totbrackets = 0;

	int hash(char *str)
	{
		int value = 0,i;
		for(i = 0 ; i < strlen(str) ; i++)
		{
			value = 10*value + (str[i] - 'A');
			value = value % 1001;
			while(value < 0)
				value = value + 1001;
		}
		return value;
	}

	int getbrackets(char *str1){
		int value = hash(str1);
		if(ST[value].length == 0)
			return 12;
		if(strcmp(ST[value].name,str1)==0)
			return ST[value].brackets;
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					return ST[i].brackets;
				}
			}
			return 13;
		}
	}

	void setbrackets(char *str1, int brackets){
		int i;
		for(i = 0 ; i < 1001 ; i++)
		{
			if(strcmp(ST[i].name,str1)==0 )
			{
				ST[i].brackets = brackets;
				return;
			}
		}
	}


	int lookupST(char *str)
	{
		int value = hash(str);
		if(ST[value].length == 0)
		{
			return 0;
		}
		else if(strcmp(ST[value].name,str)==0)
		{

			return value;
		}
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str)==0)
				{

					return i;
				}
			}
			return 0;
		}
	}

	int lookupCT(char *str)
	{
		int value = hash(str);
		if(CT[value].length == 0)
			return 0;
		else if(strcmp(CT[value].name,str)==0)
			return 1;
		else
		{
			int i;	
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(CT[i].name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}


	void insertSTline(char *str1, int line)
	{
		int value = hash(str1);
		if(strcmp(ST[value].name,str1)==0)
			ST[value].lineno = line;
		else
		{
			int i;	
			for(i = (value + 1) ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					ST[i].lineno = line;
				}
			}
		}
	}

	void insertSTparamstype(char *str1, char *str2)
	{
		int value = hash(str1);
	    if(strcmp(ST[value].name,str1)==0)
			{
				int j;
				for(j=0;j<100;j++)
				{
					if(ST[value].params_types[j][0]=='\0')
					{
						strcpy(ST[value].params_types[j],str2);
						break;
					}
				}
			}
		else
		{
			int i,j;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					int j;
					for(j=0;j<100;j++)
					{
						if(ST[i].params_types[j][0]=='\0')
						{
							strcpy(ST[i].params_types[j],str2);
							break;
						}
					}
				}
			}
		}

	}

	int check_params_type(char *str, char types[100][100], int n)
	{
		int value = hash(str),j,k;
	    if(strcmp(ST[value].name,str)==0)
			{
				for(j=0;j<n;j++)
				{
					if(strcmp(ST[value].params_types[j],types[j]))
					{
						/*
						for(k=0;k<n;k++)
						{
							printf("\n%s\n",ST[value].params_types[j]);
						}
						printf("\n%s....%s....%s....%d\n",ST[value].name,ST[value].params_types[j],types[j],j);
						*/
						return 0;
					}
				}
			}
		else
		{
			int i,j;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str)==0)
				{
					for(j=0;j<n;j++)
					{
						if(strcmp(ST[i].params_types[j],types[j]))
						{
							/*
							for(int k=0;k<n;k++)
							{
								printf("\n%s\n",ST[i].params_types[j]);
							}
							printf("\n%s....%s....%s....%d\n",ST[i].name,ST[i].params_types[j],types[j],j);
							*/
							return 0;
						}
					}
				}
			}
		}


		return 1;
	}

	void insertST(char *str1, char *str2)
	{
		if(lookupST(str1))
		{
			if(strcmp(ST[lookupST(str1)].class,"Identifier")==0 && strcmp(str2,"Array Identifier")==0)
			{
				printf("Error use of array\n");
				exit(0);
			}
			return;
		}
		else
		{
			int value = hash(str1);
			if(ST[value].length == 0)
			{
				int j;
				strcpy(ST[value].name,str1);
				strcpy(ST[value].class,str2);
				ST[value].length = strlen(str1);
				ST[value].initnestval = 9999;
				ST[value].nestval = 9999;
				ST[value].params_count = -1;
				insertSTline(str1,yylineno);
				for(j=0;j<100;j++)
					ST[value].params_types[j][0] = '\0';
				return;
			}

			int pos = 0,i;

			for (i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,str1);
			strcpy(ST[pos].class,str2);
			ST[pos].length = strlen(str1);
			ST[pos].initnestval = 9999;
			ST[pos].nestval = 9999;
			ST[pos].params_count = -1;
			int j;
			for(j=0;j<100;j++)
				ST[value].params_types[j][0] = '\0';
		}
	}

	void insertSTtype(char *str1, char *str2)
	{
		int value = hash(str1);
		if(strcmp(ST[value].name,str1)==0)
			strcpy(ST[value].type,str2);
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0)
				{
					strcpy(ST[i].type,str2);
				}
			}
		}


    }

	void insertSTvalue(char *str1, char *str2)
	{
		int value = hash(str1);
		if(strcmp(ST[value].name,str1)==0 && ST[value].nestval == currnest)
			strcpy(ST[value].value,str2);
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,str1)==0 && ST[i].nestval == currnest)
				{
					strcpy(ST[i].value,str2);
				}
			}
		}

	}


	void insertSTnest(char *s, int nest)
	{
		if(lookupST(s) && ST[lookupST(s)].nestval != 9999)
		{
             int pos = 0;
             int value = hash(s);
             int i;
			for (i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(ST[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(ST[pos].name,s);
			strcpy(ST[pos].class,"Identifier");
			ST[pos].length = strlen(s);
			ST[pos].initnestval = nest;
			ST[pos].nestval = nest;
			ST[pos].params_count = -1;
			ST[pos].lineno = yylineno;
		}
		else
		{
			int i;
			for(i = 0 ; i < 1001 ; i++)
			{
				if(strcmp(ST[i].name,s)==0 )
				{
					ST[i].initnestval = nest;
					ST[i].nestval = nest;
				}
			}
		}
	}

	void insertSTparamscount(char *s, int count)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			ST[value].params_count = count;
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					ST[i].params_count = count;
				}
			}
		}

	}

	int getSTparamscount(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			return ST[value].params_count;
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].params_count;
				}
			}
		}

		return -2;
	}

	void insertSTF(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			strcpy(ST[value].class,"Function");
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					strcpy(ST[i].class,"Function");
				}
			}
		}



	}

	void insertCT(char *str1, char *str2)
	{
		if(lookupCT(str1))
			return;
		else
		{
			int value = hash(str1);
			if(CT[value].length == 0)
			{
				strcpy(CT[value].name,str1);
				strcpy(CT[value].type,str2);
				CT[value].length = strlen(str1);
				return;
			}

			int pos = 0,i;

			for (i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(CT[i].length == 0)
				{
					pos = i;
					break;
				}
			}

			strcpy(CT[pos].name,str1);
			strcpy(CT[pos].type,str2);
			CT[pos].length = strlen(str1);
		}
	}

	void deletedata (int nesting)
	{
		int i;
		for(i = 0 ; i < 1001 ; i++)
		{
			if(ST[i].nestval == nesting)
			{
				ST[i].nestval = 99999;
			}
		}


	}


	int checkscope(char *s)
	{
		int flag = 0,i;
		for(i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].name,s)==0)
			{
				if(ST[i].nestval > currnest)
				{
					flag = 1;
				}
				else
				{
					flag = 0;
					break;
				}
			}
		}
		if(!flag)
		{
			return 1;
		}
		else
		{
			return 0;
		}
	}

	int check_id_is_func(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
		{
			if(strcmp(ST[value].class,"Function")==0)
					return 1;
		}
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					if(strcmp(ST[i].class,"Function")==0);
					return 1;
				}
			}
		}
		return 0;
	}

	int checkarray(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			{
				if(strcmp(ST[value].class,"Array Identifier")==0)
				{
					return 0;
				}
			}
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					if(strcmp(ST[i].class,"Array Identifier")==0)
					{
						return 0;
					}
				}
			}
		}

		return 1;
	}

	int duplicate(char *s)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			{
				if(ST[value].nestval == currnest)
				{
			        return 1;
				}
			}
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					if(ST[i].nestval == currnest)
					{
						return 1;
					}
				}
			}
		}

		return 0;
	}

	int check_duplicate(char* str)
	{
		int value = hash(str);
		if(strcmp(ST[value].name, str) == 0 && strcmp(ST[value].class, "Function") == 0)
			{
				printf("Function redeclaration not allowed\n");
				exit(0);
			}
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0)
				{
					printf("Function redeclaration not allowed\n");
					exit(0);
				}
			}
		}

	}

	int check_declaration(char* str, char *check_type)
	{
		int value = hash(str);
		if(strcmp(ST[value].name, str) == 0 && strcmp(ST[value].class, "Function") == 0 || strcmp(ST[value].name,"printf")==0 )
				return 1;
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name, str) == 0 && strcmp(ST[i].class, "Function") == 0 || strcmp(ST[i].name,"printf")==0)
				{
                    return 1;
    			}
			}
		}

		return 0;
	}

	int check_params(char* type_specifier)
	{
		if(!strcmp(type_specifier, "void"))
		{
			printf("Parameters cannot be of type void\n");
			exit(0);
		}
		return 0;
	}

	char gettype(char *s, int flag)
	{
		int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			return ST[value].type[0];
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].type[0];
				}
			}
		}

	}

	char *gettypestr(char *s)
	{	int value = hash(s);
		if(strcmp(ST[value].name,s)==0)
			return ST[value].type;
		else
		{
			int i;
			for(i = value + 1 ; i!=value ; i = (i+1)%1001)
			{
				if(strcmp(ST[i].name,s)==0)
				{
					return ST[i].type;
				}
			}
		}

	}

	void printST()
	{
		int i;
		printf("%10s | %15s | %10s | %10s | %10s | %15s | %10s |\n","SYMBOL", "CLASS", "TYPE","VALUE", "LINE NO", "NESTING", "PARAMS COUNT");
		for(i=0;i<100;i++) {
			printf("-");
		}
		printf("\n");
		for(i = 0 ; i < 1001 ; i++)
		{
			if(ST[i].length == 0)
			{
				continue;
			}
			printf("%10s | %15s | %10s | %10s | %10d | %15d | %10d |\n",ST[i].name, ST[i].class, ST[i].type, ST[i].value, ST[i].lineno, ST[i].initnestval, ST[i].params_count);
		}
		for(i=0;i<1001;i++)
		{
			if(!strcmp(ST[i].class,"Function"))
			{
				int j;
				printf("\n%s : ",ST[i].name);
				for(j=0;j<ST[i].params_count;j++)
				{
					printf(" %s ",ST[i].params_types[j]);
				}
			}
		}
    }


	void printCT()
	{
		int i;
		printf("%10s | %15s\n","NAME", "TYPE");
		for(i=0;i<81;i++) {
			printf("-");
		}
		printf("\n");
		for(i = 0 ; i < 1001 ; i++)
		{
			if(CT[i].length == 0)
				continue;

			printf("%10s | %15s\n",CT[i].name, CT[i].type);
		}
	}
	char curid[20];
	char curtype[20];
	char curval[20];

#line 1382 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 736 ".\\filewind.l"

#line 1535 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 192 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 781 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 737 ".\\filewind.l"
{yylineno++;}
	YY_BREAK
case 2:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 738 ".\\filewind.l"
{ }
	YY_BREAK
case 3:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 739 ".\\filewind.l"
{ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 740 ".\\filewind.l"
{ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 741 ".\\filewind.l"
{ }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 742 ".\\filewind.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 743 ".\\filewind.l"
{ return(';'); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 744 ".\\filewind.l"
{ return(','); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 745 ".\\filewind.l"
{ return('{'); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 746 ".\\filewind.l"
{ return('}'); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 747 ".\\filewind.l"
{ return('('); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 748 ".\\filewind.l"
{ return(')'); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 749 ".\\filewind.l"
{ return('['); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 750 ".\\filewind.l"
{ return(']'); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 751 ".\\filewind.l"
{ return(':'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 752 ".\\filewind.l"
{ return('.'); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 754 ".\\filewind.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword");return CHAR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 755 ".\\filewind.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 756 ".\\filewind.l"
{ insertST(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 757 ".\\filewind.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return FLOAT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 758 ".\\filewind.l"
{ insertST(yytext, "Keyword"); return WHILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 759 ".\\filewind.l"
{ insertST(yytext, "Keyword"); return DO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 760 ".\\filewind.l"
{ insertST(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 761 ".\\filewind.l"
{ insertST(yytext, "Keyword"); return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 762 ".\\filewind.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return INT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 763 ".\\filewind.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return LONG;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 764 ".\\filewind.l"
{ insertST(yytext, "Keyword"); return RETURN;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 765 ".\\filewind.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return SHORT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 766 ".\\filewind.l"
{ strcpy(curtype,yytext); insertST(yytext, "Keyword"); return SIGNED;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 767 ".\\filewind.l"
{ insertST(yytext, "Keyword"); return SIZEOF;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 768 ".\\filewind.l"
{ strcpy(curtype,yytext);   insertST(yytext, "Keyword");  return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 769 ".\\filewind.l"
{ insertST(yytext, "Keyword");   return UNSIGNED;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 770 ".\\filewind.l"
{ strcpy(curtype,yytext);   insertST(yytext, "Keyword");  return VOID;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 771 ".\\filewind.l"
{ insertST(yytext, "Keyword");  return BREAK;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 775 ".\\filewind.l"
{ return increment_operator; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 776 ".\\filewind.l"
{ return decrement_operator; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 777 ".\\filewind.l"
{ return leftshift_operator; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 778 ".\\filewind.l"
{ return rightshift_operator; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 779 ".\\filewind.l"
{ return lessthan_assignment_operator; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 780 ".\\filewind.l"
{ return lessthan_operator; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 781 ".\\filewind.l"
{ return greaterthan_assignment_operator; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 782 ".\\filewind.l"
{ return greaterthan_operator; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 783 ".\\filewind.l"
{ return equality_operator; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 784 ".\\filewind.l"
{ return inequality_operator; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 785 ".\\filewind.l"
{ return AND_operator; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 786 ".\\filewind.l"
{ return OR_operator; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 787 ".\\filewind.l"
{ return caret_operator; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 788 ".\\filewind.l"
{ return multiplication_assignment_operator; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 789 ".\\filewind.l"
{ return division_assignment_operator; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 790 ".\\filewind.l"
{ return modulo_assignment_operator; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 791 ".\\filewind.l"
{ return addition_assignment_operator; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 792 ".\\filewind.l"
{ return subtraction_assignment_operator; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 793 ".\\filewind.l"
{ return leftshift_assignment_operator; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 794 ".\\filewind.l"
{ return rightshift_assignment_operator; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 795 ".\\filewind.l"
{ return AND_assignment_operator; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 796 ".\\filewind.l"
{ return XOR_assignment_operator; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 797 ".\\filewind.l"
{ return OR_assignment_operator; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 798 ".\\filewind.l"
{ return amp_operator; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 799 ".\\filewind.l"
{ return exclamation_operator; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 800 ".\\filewind.l"
{ return tilde_operator; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 801 ".\\filewind.l"
{ return subtract_operator; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 802 ".\\filewind.l"
{ return add_operator; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 803 ".\\filewind.l"
{ return multiplication_operator; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 804 ".\\filewind.l"
{ return division_operator; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 805 ".\\filewind.l"
{ return modulo_operator; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 806 ".\\filewind.l"
{ return pipe_operator; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 807 ".\\filewind.l"
{ return assignment_operator;}
	YY_BREAK
case 68:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 809 ".\\filewind.l"
{strcpy(curval,yytext); insertCT(yytext,"String Constant"); return string_constant;}
	YY_BREAK
case 69:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 810 ".\\filewind.l"
{strcpy(curval,yytext); insertCT(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 70:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 4;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 811 ".\\filewind.l"
{strcpy(curval,yytext); insertCT(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 71:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 812 ".\\filewind.l"
{strcpy(curid,yytext); insertST(yytext, "Array Identifier");  return array_identifier;}
	YY_BREAK
case 72:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 813 ".\\filewind.l"
{strcpy(curval,yytext); insertCT(yytext, "Number Constant"); yylval = atoi(yytext); return integer_constant;}
	YY_BREAK
case 73:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 814 ".\\filewind.l"
{strcpy(curval,yytext); insertCT(yytext, "Floating Constant"); return float_constant;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 815 ".\\filewind.l"
{strcpy(curid,yytext); insertST(curid,"Identifier"); return identifier;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 816 ".\\filewind.l"
{
		if(yytext[0]=='#')
		{
			printf("Error in Pre-Processor directive at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='/')
		{
			printf("ERR_UNMATCHED_COMMENT at line no. %d\n",yylineno);
		}
		else if(yytext[0]=='"')
		{
			printf("ERR_INCOMPLETE_STRING at line no. %d\n",yylineno);
		}
		else
		{
			printf("ERROR at line no. %d\n",yylineno);
		}
		printf("%s\n", yytext);
		return 0;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 837 ".\\filewind.l"
ECHO;
	YY_BREAK
#line 2049 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 192 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 192 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 191);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 837 ".\\filewind.l"

